name: avatars
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  image_gallery_saver: ^1.7.1
  palette_generator: ^0.3.3+2
  device_info_plus: ^8.1.0
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/icons/
